[tool.poetry]
name = "mlx5w1t1"
version = "0.1.0"
description = ""
authors = ["Kaleb Sofer <kalebsofer@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
jupyter = "^1.0.0"  # Add this line
ipykernel = "^6.29.0"  # Add this line if not already present
sqlalchemy = "^2.0.35"
psycopg2 = "^2.9.9"
<<<<<<< HEAD
polars = "^1.9.0"
connectorx = "^0.3.3"
matplotlib = "^3.9.2"
pyarrow = "^17.0.0"
=======
>>>>>>> 5c63ad957cdb3ee40404cf9cc6b8195f59863012
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
